import 'dart:io';

void main() {
  final lib = Directory('lib');
  final files = lib
      .listSync(recursive: true)
      .whereType<File>()
      .where((file) => file.path.endsWith('.dart'))
      .where((file) => !file.path.endsWith('.g.dart'))
      .where((file) => !file.path.endsWith('.freezed.dart'))
      .map((file) => file.path.replaceAll('\\', '/'))
      .toList()
    ..sort();

  final imports = files.map((path) {
    final packagePath = path.replaceFirst('lib/', 'package:shorts_ai/');
    return "import '$packagePath';";
  }).join('\n');

  final output = '''
// Generated by tool/generate_coverage_helper.dart.
// ignore_for_file: unused_import, directives_ordering

$imports

void main() {}
''';

  File('test/coverage_helper_test.dart').writeAsStringSync(output);
  stdout.writeln(
      'Wrote test/coverage_helper_test.dart with ${files.length} imports.');
}
